Added idp_userid column to users table
bcgov/registries-search pull request #205
Opened 2022-11-23 21:44 UTC by pwei1018

*Issue #:* /bcgov/entity###
https://github.com/bcgov/entity/issues/14367

*Description of changes:*
1. add idp_userid column to users table;

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the PPR license (Apache 2.0).

2022-11-23 22:00 UTC, kialj876 approved these changes

2022-11-23 22:01 UTC, kialj876 requested changes
Oh hang on can you add this column to the model too?

2022-11-23 22:07 UTC, kialj876 approved these changes
ah nvm -- as long as it gets added to the model later this is fine

2022-11-23 22:27 UTC, thorwolpert requested changes

2022-11-23 22:27 UTC, thorwolpert commented on search-api/migrations/versions/f7d39c77458f_add_idp_userid_to_users.py
> +down_revision = '065057716b7a'
Will need to be against revision 6072ec70fb7a

2022-11-23 22:34 UTC, thorwolpert approved these changes

2022-11-24 05:24 UTC, lekshmimallika-aot approved these changes

2022-11-24 16:50 UTC, merged